### PR TITLE
Pull request for issue #1

### PR DESCRIPTION
**Pull request by HoochDeveloper**
Issue: https://github.com/italia/cie-nis-sdk/issues/1

Samples for reading NIS in C++, Java, Objective-C

### CODE REVIEW

**Comment by alexrj** [comment]
Hello!

I initially merged your pull request because I thought about having a single cie-nis-sdk repository with your code and the Python one (from the other pull request) but I realized this would prevent us from having TravisCI running.
So I'm going to create additional individual repositories for your code: cie-nis-java-sdk, cie-nis-objc-sdk, cie-nis-cpp-sdk.

I have one question before proceeding: why did you relicense the repository from BSD-3 (our preferred license) to Apache?

**Comment by duncanwilcox** [comment]
The MacOS code is derivative of https://github.com/dirkx/CryptoTokenKit-TrivialExample-OpenSC which is Apache licensed.

**Comment by alexrj** [comment]
Thank you for the clarification. Then can we keep BSD-3 for Java and C++?

**Comment by alexrj** [comment]
I just created three new repositories for your code and pulled it preserving history:
https://github.com/italia/cie-nis-cpp-sdk
https://github.com/italia/cie-nis-java-sdk
https://github.com/italia/cie-nis-objc-sdk

Thank you for your contribution, and welcome to the community of Developers Italia as maintainers of the above repositories, on which you now have full admin rights 😃 
(Remember: with great power comes great responsibility.)

I also invited you to become part of the [italia](https://github.com/italia) organization, so that you can display its logo on your profile (don't forget to [change the visibility](https://github.com/orgs/italia/people) after you accept the invitation!).

**Pull request merged**
